-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:31:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escuela` ;

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`PROFESOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`PROFESOR` ;

CREATE TABLE IF NOT EXISTS `escuela`.`PROFESOR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`ALUMNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`ALUMNO` ;

CREATE TABLE IF NOT EXISTS `escuela`.`ALUMNO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`MATERIA` ;

CREATE TABLE IF NOT EXISTS `escuela`.`MATERIA` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `version` FLOAT NULL,
  `grado` INT NULL,
  `MATERIAcol` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`TIENE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`TIENE` ;

CREATE TABLE IF NOT EXISTS `escuela`.`TIENE` (
  `ALUMNO_id` INT NOT NULL,
  `PROFESOR_id` INT NOT NULL,
  PRIMARY KEY (`ALUMNO_id`, `PROFESOR_id`),
  INDEX `fk_ALUMNO_has_PROFESOR_PROFESOR1_idx` (`PROFESOR_id` ASC) VISIBLE,
  INDEX `fk_ALUMNO_has_PROFESOR_ALUMNO_idx` (`ALUMNO_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_has_PROFESOR_ALUMNO`
    FOREIGN KEY (`ALUMNO_id`)
    REFERENCES `escuela`.`ALUMNO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNO_has_PROFESOR_PROFESOR1`
    FOREIGN KEY (`PROFESOR_id`)
    REFERENCES `escuela`.`PROFESOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`CURSA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`CURSA` ;

CREATE TABLE IF NOT EXISTS `escuela`.`CURSA` (
  `ALUMNO_id` INT NOT NULL,
  `MATERIA_codigo` INT NOT NULL,
  PRIMARY KEY (`ALUMNO_id`, `MATERIA_codigo`),
  INDEX `fk_ALUMNO_has_MATERIA_MATERIA1_idx` (`MATERIA_codigo` ASC) VISIBLE,
  INDEX `fk_ALUMNO_has_MATERIA_ALUMNO1_idx` (`ALUMNO_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_has_MATERIA_ALUMNO1`
    FOREIGN KEY (`ALUMNO_id`)
    REFERENCES `escuela`.`ALUMNO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNO_has_MATERIA_MATERIA1`
    FOREIGN KEY (`MATERIA_codigo`)
    REFERENCES `escuela`.`MATERIA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`IMPARTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`IMPARTE` ;

CREATE TABLE IF NOT EXISTS `escuela`.`IMPARTE` (
  `PROFESOR_id` INT NOT NULL,
  `MATERIA_codigo` INT NOT NULL,
  PRIMARY KEY (`PROFESOR_id`, `MATERIA_codigo`),
  INDEX `fk_PROFESOR_has_MATERIA_MATERIA1_idx` (`MATERIA_codigo` ASC) VISIBLE,
  INDEX `fk_PROFESOR_has_MATERIA_PROFESOR1_idx` (`PROFESOR_id` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_has_MATERIA_PROFESOR1`
    FOREIGN KEY (`PROFESOR_id`)
    REFERENCES `escuela`.`PROFESOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESOR_has_MATERIA_MATERIA1`
    FOREIGN KEY (`MATERIA_codigo`)
    REFERENCES `escuela`.`MATERIA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
